import type { JSONSchema7 } from "json-schema";
import type { WorkflowDefinition } from "../workflow/types.js";
import type { GeneratorEndpoint } from "./types.js";
import { escapeBlockComment } from "./escape.js";

function indentJson(value: unknown, indent = "const "): string {
  void indent;
  return JSON.stringify(value, null, 2)
    .split("\n")
    .map((line, i) => (i === 0 ? line : "  " + line))
    .join("\n");
}

/** Map a JSON-schema param entry to a Zod expression usable under Zod 3 and 4. */
function zodForParam(schema: JSONSchema7 | undefined): string {
  const type =
    typeof schema?.type === "string" ? schema.type.toLowerCase() : "";
  switch (type) {
    case "string":
      return "z.string()";
    case "number":
    case "integer":
      return "z.number()";
    case "boolean":
      return "z.boolean()";
    case "array":
      return "z.array(z.any())";
    case "object":
      return "z.record(z.string(), z.any())";
    default:
      return "z.any()";
  }
}

function zodShape(params: JSONSchema7): string {
  const props =
    (params.properties as Record<string, JSONSchema7> | undefined) ?? {};
  const required = new Set(
    Array.isArray(params.required) ? params.required : [],
  );
  const entries = Object.entries(props).map(([key, schema]) => {
    const base = zodForParam(schema);
    const desc = schema?.description
      ? `.describe(${JSON.stringify(schema.description)})`
      : "";
    const optional = required.has(key) ? "" : ".optional()";
    return `      ${JSON.stringify(key)}: ${base}${desc}${optional}`;
  });
  return entries.length > 0 ? `{\n${entries.join(",\n")}\n    }` : "{}";
}

/** Generate `src/tools/<name>.ts` — the workflow embedded as data + handler. */
export function generateToolFile(workflow: WorkflowDefinition): string {
  return `/**
 * ${escapeBlockComment(workflow.name)} — ${escapeBlockComment(workflow.description)}
 * Steps: ${escapeBlockComment(workflow.steps.map((s) => s.id).join(" -> "))}. Generated by mcp-server-generator.
 */
import { runWorkflow } from "../engine/index.js";
import type { WorkflowDefinition } from "../engine/types.js";
import type {
  EndpointInfo,
  WorkflowClient,
  WorkflowServer,
} from "../engine/executor.js";

const workflow: WorkflowDefinition = ${indentJson(workflow)};

export const tool = {
  name: ${JSON.stringify(workflow.name)},
  description: ${JSON.stringify(workflow.description)},
};

export interface ToolContext {
  client: WorkflowClient;
  server: WorkflowServer;
  endpoints: Record<string, EndpointInfo>;
}

export function createHandler(ctx: ToolContext) {
  return async (args: Record<string, unknown>) => {
    const result = await runWorkflow(workflow, args, ctx);
    return {
      content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }],
      ...(result.status === "error" ? { isError: true } : {}),
    };
  };
}
`;
}

function sampleArgValue(schema: JSONSchema7 | undefined): unknown {
  const type =
    typeof schema?.type === "string" ? schema.type.toLowerCase() : "";
  switch (type) {
    case "number":
    case "integer":
      return 1;
    case "boolean":
      return true;
    case "array":
      return [];
    case "object":
      return {};
    case "string":
    default:
      return "test";
  }
}

function sampleArgs(params: JSONSchema7): Record<string, unknown> {
  const props =
    (params.properties as Record<string, JSONSchema7> | undefined) ?? {};
  const out: Record<string, unknown> = {};
  for (const [key, schema] of Object.entries(props)) {
    out[key] = sampleArgValue(schema);
  }
  return out;
}

/** Generate `src/tests/setup.ts` — network-free mocks over the real workflow engine. */
export function generateTestSetup(): string {
  return `/**
 * Shared test setup: in-memory mocks so these tests run the real engine with no network
 * and no LLM. Generated by mcp-server-generator.
 */
import type {
  ApiResponse,
  EndpointInfo,
  WorkflowClient,
  WorkflowServer,
} from "../engine/executor.js";
import { endpointMap } from "../endpoints.js";

/** A generic, field-rich record so downstream steps find something to read. */
function mockRecord() {
  return {
    _id: "mock-id",
    id: "mock-id",
    name: "mock",
    fname: "mock",
    username: "mockuser",
    msg: "mock message",
    text: "mock text",
    title: "mock title",
    summary: "mock summary",
    url: "https://example.com/mock",
    ts: "2020-01-01T00:00:00.000Z",
    u: { _id: "mock-user", username: "mockuser", name: "Mock User" },
  };
}

/** A permissive mock client — every request "succeeds" with generic data. */
export function createMockClient(): WorkflowClient {
  return {
    async request(): Promise<ApiResponse> {
      const record = mockRecord();
      return {
        ok: true,
        status: 200,
        data: {
          success: true,
          messages: [record],
          channels: [record],
          items: [record],
          ...record,
        },
      };
    },
  };
}

/** A mock MCP server: sampling returns JSON; elicitation always accepts. */
export function createMockServer(): WorkflowServer {
  return {
    async createMessage() {
      return {
        content: {
          type: "text",
          text: JSON.stringify({
            summary: "mock summary",
            safe: ["mock"],
            risky: [],
            flagged: ["mock"],
            approved: true,
          }),
        },
      };
    },
    async elicitInput() {
      return { action: "accept", content: { approved: true } };
    },
  };
}

export function mockEndpoints(): Record<string, EndpointInfo> {
  return endpointMap;
}
`;
}

/** Generate `src/tests/<name>.test.ts` — a per-workflow smoke test. */
export function generateToolTest(
  workflow: WorkflowDefinition,
  moduleName: string,
): string {
  const args = JSON.stringify(sampleArgs(workflow.params), null, 2)
    .split("\n")
    .map((line, i) => (i === 0 ? line : "  " + line))
    .join("\n");

  return `/**
 * Generated tests for "${workflow.name}": metadata, endpoint wiring, and an engine run.
 */
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { tool, createHandler } from "../tools/${moduleName}.js";
import { endpointMap } from "../endpoints.js";
import { createMockClient, createMockServer, mockEndpoints } from "./setup.js";

const sampleArgs = ${args};
const requiredEndpoints: string[] = ${JSON.stringify(workflow.requiredEndpoints)};

describe(${JSON.stringify(workflow.name + " workflow tool")}, () => {
  it("exposes the expected tool metadata", () => {
    assert.equal(tool.name, ${JSON.stringify(workflow.name)});
    assert.ok(tool.description.length > 0, "tool has a description");
  });

  it("declares every endpoint it calls in the endpoint map", () => {
    for (const operationId of requiredEndpoints) {
      assert.ok(
        endpointMap[operationId],
        \`endpoint "\${operationId}" is missing from the endpoint map\`,
      );
    }
  });

  it("runs end-to-end on mock data and returns a well-formed MCP result", async () => {
    const handler = createHandler({
      client: createMockClient(),
      server: createMockServer(),
      endpoints: mockEndpoints(),
    });

    const result = await handler(sampleArgs);

    assert.ok(Array.isArray(result.content), "result has a content array");
    assert.equal(result.content[0].type, "text");

    const run = JSON.parse(result.content[0].text) as {
      status: string;
      completedSteps: string[];
    };
    assert.ok(
      ["success", "partial", "aborted", "error"].includes(run.status),
      \`unexpected workflow status: \${run.status}\`,
    );
    assert.ok(Array.isArray(run.completedSteps), "result reports completed steps");
  });
});
`;
}

/** Generate `src/endpoints.ts`. The spec's declared locations stop the engine guessing by verb. */
export function generateEndpointMap(endpoints: GeneratorEndpoint[]): string {
  const entries = endpoints
    .map((ep) => {
      const parts = [
        `method: ${JSON.stringify(ep.method.toUpperCase())}`,
        `path: ${JSON.stringify(ep.path)}`,
      ];
      if (ep.queryParams && ep.queryParams.length > 0) {
        parts.push(`queryParams: ${JSON.stringify(ep.queryParams)}`);
      }
      if (ep.headerParams && ep.headerParams.length > 0) {
        parts.push(`headerParams: ${JSON.stringify(ep.headerParams)}`);
      }
      if (ep.auth === false) parts.push(`auth: false`);
      return `  ${JSON.stringify(ep.operationId)}: { ${parts.join(", ")} },`;
    })
    .join("\n");
  return `/**
 * Endpoint registry: operationId -> method, path, declared parameter locations, and \`auth\`.
 * An unlisted parameter follows the verb (GET -> query string, otherwise JSON body).
 */
export const endpointMap: Record<
  string,
  {
    method: string;
    path: string;
    queryParams?: string[];
    headerParams?: string[];
    auth?: boolean;
  }
> = {
${entries}
};
`;
}

export type Transport = "stdio" | "http";

/** Generate `src/server.ts`. `clientModule` names the REST client; `transport` is stdio or HTTP. */
export function generateServerEntry(
  serverName: string,
  workflows: WorkflowDefinition[],
  moduleNames: string[],
  clientModule = "rc-client",
  transport: Transport = "stdio",
): string {
  const toolImports = workflows
    .map(
      (_w, i) =>
        `import { tool as wfTool${i}, createHandler as createHandler${i} } from "./tools/${moduleNames[i]}.js";`,
    )
    .join("\n");

  const registrations = workflows
    .map(
      (w, i) =>
        `  server.registerTool(\n` +
        `    wfTool${i}.name,\n` +
        `    { description: wfTool${i}.description, inputSchema: ${zodShape(w.params)} },\n` +
        `    createHandler${i}({ client, server: workflowServer, endpoints: endpointMap }) as never,\n` +
        `  );`,
    )
    .join("\n");

  const transportImport =
    transport === "http"
      ? `import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { createServer } from "node:http";
import { createHash, randomUUID, timingSafeEqual } from "node:crypto";`
      : `import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";`;

  const startup =
    transport === "http"
      ? httpStartup(serverName, workflows.length)
      : stdioStartup(serverName, workflows.length);

  return `#!/usr/bin/env node
/**
 * ${escapeBlockComment(serverName)} — MCP server, ${workflows.length} workflow tool(s), ${transport} transport.
 * Generated by mcp-server-generator.
 */
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
${transportImport}
import { z } from "zod";
import { endpointMap } from "./endpoints.js";
import { client, initAuth } from "./${clientModule}.js";
import type { WorkflowServer } from "./engine/executor.js";
${toolImports}

/** Bridges the client's sampling (its LLM) and elicitation (its user) to the engine. */
function makeWorkflowServer(mcp: McpServer): WorkflowServer {
  return {
    async createMessage(message) {
      const res = await mcp.server.createMessage({
        messages: [
          { role: "user", content: { type: "text", text: message.prompt } },
        ],
        ...(message.systemPrompt ? { systemPrompt: message.systemPrompt } : {}),
        maxTokens: message.maxTokens ?? 1024,
      });
      const text =
        res.content && res.content.type === "text" ? res.content.text : "";
      return { content: { type: "text", text } };
    },
    async elicitInput(params) {
      const res = await mcp.server.elicitInput({
        message: params.message,
        requestedSchema: params.requestedSchema as never,
      });
      return { action: res.action, content: res.content };
    },
  };
}

/** A factory, not a singleton: the SDK refuses to connect a server already bound to a transport. */
function createMcpServer(): McpServer {
  const server = new McpServer({ name: ${JSON.stringify(serverName)}, version: "1.0.0" });
  const workflowServer = makeWorkflowServer(server);

${registrations}

  return server;
}

// ─── Graceful shutdown ───────────────────────────────────────────────────────

const SHUTDOWN_TIMEOUT_MS = 5000;
let shuttingDown = false;

/** Run \`cleanup\` once on SIGINT/SIGTERM/SIGHUP, timed out so it cannot wedge exit. */
function installGracefulShutdown(cleanup: () => Promise<void>): void {
  const shutdown = (code: number) => {
    if (shuttingDown) return;
    shuttingDown = true;
    const timer = setTimeout(() => process.exit(code), SHUTDOWN_TIMEOUT_MS);
    timer.unref();
    Promise.resolve(cleanup())
      .catch(() => {})
      .finally(() => process.exit(code));
  };
  process.on("SIGINT", () => shutdown(0));
  process.on("SIGTERM", () => shutdown(0));
  process.on("SIGHUP", () => shutdown(0));
}

// ─── Start ───────────────────────────────────────────────────────────────────

async function main() {
  await initAuth();
${startup}
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
`;
}

/** stdio startup: one server, one transport, for the life of the process. */
function stdioStartup(serverName: string, toolCount: number): string {
  return `  const server = createMcpServer();
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error(${JSON.stringify(serverName)} + " running — ${toolCount} workflow tool(s)");
  installGracefulShutdown(async () => {
    await server.close();
  });`;
}

/** Defaults are closed — loopback, fail-closed Host allowlist — since this can invoke every tool. */
function httpStartup(serverName: string, toolCount: number): string {
  return `  const PORT = (() => {
    const raw = process.env.MCP_PORT || "3100";
    const n = Number(raw);
    if (!Number.isInteger(n) || n < 1 || n > 65535) {
      console.error('Invalid MCP_PORT "' + raw + '": must be an integer between 1 and 65535.');
      process.exit(1);
    }
    return n;
  })();

  // Loopback by default; widening it also requires widening MCP_ALLOWED_HOSTS.
  const BIND_HOST = process.env.MCP_BIND_HOST || "127.0.0.1";
  const AUTH_TOKEN = process.env.MCP_AUTH_TOKEN || "";

  // DNS-rebinding protection: a rebound request arrives with the attacker's own hostname.
  const ALLOWED_HOSTS = new Set(
    (process.env.MCP_ALLOWED_HOSTS ||
      "localhost:" + PORT + ",127.0.0.1:" + PORT + ",[::1]:" + PORT)
      .split(",")
      .map((h) => h.trim().toLowerCase())
      .filter(Boolean),
  );
  const ALLOWED_ORIGINS = new Set(
    (process.env.MCP_ALLOWED_ORIGINS || "")
      .split(",")
      .map((o) => o.trim())
      .filter(Boolean),
  );

  /** Fixed-length digests: no short-circuit on the first differing byte, no length leak. */
  function safeCompare(a: string, b: string): boolean {
    return timingSafeEqual(
      createHash("sha256").update(a).digest(),
      createHash("sha256").update(b).digest(),
    );
  }

  /** RFC 7235 makes the scheme case-insensitive, so "bearer" is a legal spelling. */
  function bearerCredential(header: string | string[] | undefined): string | null {
    if (typeof header !== "string") return null;
    const match = /^\\s*Bearer\\s+(.+?)\\s*$/i.exec(header);
    return match ? match[1] : null;
  }

  if (!AUTH_TOKEN) {
    console.error("");
    console.error("  WARNING: the HTTP transport is running WITHOUT authentication.");
    console.error("  Any client that can reach this port can invoke every workflow tool");
    console.error("  using this server's credentials. Before exposing it beyond localhost,");
    console.error("  set MCP_AUTH_TOKEN or put it behind an authenticating reverse proxy.");
    console.error("");
  }

  /** No silent fallback: NaN compares false everywhere, disabling the cap and the reaper. */
  function positiveIntEnv(name: string, fallback: number): number {
    const raw = process.env[name];
    if (raw === undefined || raw === "") return fallback;
    const n = Number(raw);
    if (!Number.isInteger(n) || n < 1) {
      console.error(
        'Invalid ' + name + ' "' + raw + '": must be a positive integer.',
      );
      process.exit(1);
    }
    return n;
  }

  // A client that drops its connection without a DELETE leaves its session behind.
  const MAX_SESSIONS = positiveIntEnv("MCP_MAX_SESSIONS", 1000);
  const SESSION_TTL_MS = positiveIntEnv("MCP_SESSION_TTL_MS", 1800000);

  const sessions = new Map<
    string,
    { transport: StreamableHTTPServerTransport; lastActivity: number }
  >();

  const reaper = setInterval(
    () => {
      const now = Date.now();
      for (const [sid, session] of sessions) {
        if (now - session.lastActivity > SESSION_TTL_MS) {
          sessions.delete(sid);
          void Promise.resolve(session.transport.close()).catch(() => {});
        }
      }
    },
    Math.min(Math.max(SESSION_TTL_MS, 1000), 60000),
  );
  reaper.unref();

  const jsonError = (
    res: import("node:http").ServerResponse,
    status: number,
    code: number,
    message: string,
    headers: Record<string, string> = {},
  ) => {
    res.writeHead(status, { "Content-Type": "application/json", ...headers });
    res.end(JSON.stringify({ jsonrpc: "2.0", error: { code, message }, id: null }));
  };

  const httpServer = createServer(async (req, res) => {
    // Answered before the Host and auth gates so orchestrators can probe without a token.
    if (req.method === "GET" && (req.url === "/health" || req.url === "/healthz")) {
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ status: "ok" }));
      return;
    }

    const hostHeader = String(req.headers["host"] || "").toLowerCase();
    if (!ALLOWED_HOSTS.has(hostHeader)) {
      jsonError(res, 403, -32003, "Forbidden: Host header not allowed");
      return;
    }
    if (ALLOWED_ORIGINS.size > 0) {
      const origin = req.headers["origin"];
      if (origin && !ALLOWED_ORIGINS.has(origin)) {
        jsonError(res, 403, -32003, "Forbidden: Origin not allowed");
        return;
      }
    }

    if (AUTH_TOKEN) {
      const presented = bearerCredential(req.headers["authorization"]);
      if (presented === null || !safeCompare(presented, AUTH_TOKEN)) {
        jsonError(res, 401, -32001, "Unauthorized", { "WWW-Authenticate": "Bearer" });
        return;
      }
    }

    const sessionId = req.headers["mcp-session-id"] as string | undefined;
    const existing = sessionId ? sessions.get(sessionId) : undefined;
    if (existing) {
      existing.lastActivity = Date.now();
      await existing.transport.handleRequest(req, res);
      return;
    }

    // A POST with no session id is an "initialize" request: start a session.
    if (req.method === "POST" && !sessionId) {
      if (sessions.size >= MAX_SESSIONS) {
        jsonError(res, 503, -32000, "Server at session capacity; try again later", {
          "Retry-After": "30",
        });
        return;
      }
      const transport = new StreamableHTTPServerTransport({
        sessionIdGenerator: () => randomUUID(),
        onsessioninitialized: (sid: string) => {
          sessions.set(sid, { transport, lastActivity: Date.now() });
        },
      });
      transport.onclose = () => {
        if (transport.sessionId) sessions.delete(transport.sessionId);
      };
      const server = createMcpServer();
      await server.connect(transport);
      await transport.handleRequest(req, res);
      return;
    }

    jsonError(res, 400, -32000, "Bad Request: no valid session ID");
  });

  httpServer.listen(PORT, BIND_HOST, () => {
    console.error(
      ${JSON.stringify(serverName)} + " running on http://" + BIND_HOST + ":" + PORT +
        "/mcp — ${toolCount} workflow tool(s)",
    );
  });

  installGracefulShutdown(async () => {
    clearInterval(reaper);
    await Promise.allSettled([...sessions.values()].map((s) => s.transport.close()));
    await new Promise<void>((resolve) => httpServer.close(() => resolve()));
  });`;
}
