import type { WorkflowDefinition } from "../workflow/types.js";
import type { GeneratorEndpoint } from "./types.js";
import { escapeMarkdownCell } from "./escape.js";

/** Emits `src/rc-client.ts`. */
export function generateRcClient(): string {
  return `/**
 * Rocket.Chat HTTP client for the engine's WorkflowClient contract.
 * Auth: ROCKETCHAT_AUTH_TOKEN + ROCKETCHAT_USER_ID, else ROCKETCHAT_USER + PASSWORD login.
 * Generated by mcp-server-generator.
 */
const config = {
  baseUrl: process.env.ROCKETCHAT_URL || "http://localhost:3000",
  authToken: process.env.ROCKETCHAT_AUTH_TOKEN || "",
  userId: process.env.ROCKETCHAT_USER_ID || "",
};

const REQUEST_TIMEOUT_MS = Number(process.env.ROCKETCHAT_REQUEST_TIMEOUT_MS) || 30000;

export interface ApiResponse {
  ok: boolean;
  status: number;
  data: unknown;
}

async function parseBody(res: Response): Promise<unknown> {
  const raw = await res.text();
  if (raw.length === 0) return null;
  const contentType = res.headers.get("content-type") || "";
  if (contentType.includes("json")) {
    try {
      return JSON.parse(raw);
    } catch {
      return raw;
    }
  }
  return raw;
}

let initialized = false;

export async function initAuth(): Promise<void> {
  if (initialized) return;
  initialized = true;

  if (config.authToken && config.userId) {
    console.error("Using pre-existing Rocket.Chat auth tokens.");
    return;
  }

  const user = process.env.ROCKETCHAT_USER || "";
  const password = process.env.ROCKETCHAT_PASSWORD || "";
  if (!user || !password) {
    console.error("No Rocket.Chat credentials set — starting unconfigured.");
    return;
  }

  try {
    const res = await fetch(config.baseUrl + "/api/v1/login", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ user, password }),
    });
    const data = (await parseBody(res)) as {
      data?: { authToken?: string; userId?: string };
    };
    if (res.ok && data?.data?.authToken && data.data.userId) {
      config.authToken = data.data.authToken;
      config.userId = data.data.userId;
      console.error("Authenticated as " + user);
    } else {
      console.error("Rocket.Chat login failed (HTTP " + res.status + ").");
    }
  } catch (err) {
    console.error("Could not reach Rocket.Chat for login: " + String(err));
  }
}

function buildUrl(path: string): string {
  return path.startsWith("http") ? path : config.baseUrl + path;
}

class RocketChatClient {
  async request(
    method: string,
    path: string,
    options: {
      auth?: boolean;
      body?: Record<string, unknown>;
      headers?: Record<string, string>;
    } = {},
  ): Promise<ApiResponse> {
    const headers: Record<string, string> = { "Content-Type": "application/json" };
    if (options.auth) {
      headers["X-Auth-Token"] = config.authToken;
      headers["X-User-Id"] = config.userId;
    }
    // Assigned after the auth headers so a workflow cannot overwrite the credentials.
    for (const [k, v] of Object.entries(options.headers ?? {})) {
      if (k.toLowerCase() === "x-auth-token" || k.toLowerCase() === "x-user-id") {
        continue;
      }
      headers[k] = v;
    }

    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
    try {
      const res = await fetch(buildUrl(path), {
        method,
        headers,
        ...(options.body !== undefined ? { body: JSON.stringify(options.body) } : {}),
        signal: controller.signal,
      });
      const data = await parseBody(res);
      return { ok: res.ok, status: res.status, data };
    } catch (err) {
      return {
        ok: false,
        status: 0,
        data: err instanceof Error ? err.message : String(err),
      };
    } finally {
      clearTimeout(timer);
    }
  }
}

export const client = new RocketChatClient();
`;
}

export function generatePackageJson(serverName: string): string {
  const pkg = {
    name: serverName,
    version: "1.0.0",
    type: "module",
    engines: { node: ">=20" },
    scripts: {
      start: "node --env-file-if-exists=.env --import tsx src/server.ts",
      build: "tsc",
      "start:built": "node dist/server.js",
      test: 'tsx --test "src/tests/**/*.test.ts"',
    },
    dependencies: {
      "@modelcontextprotocol/sdk": "^1.27.1",
      acorn: "^8.17.0",
      zod: "^4.3.6",
    },
    devDependencies: {
      "@types/json-schema": "^7.0.15",
      "@types/node": "^22.0.0",
      tsx: "^4.21.0",
      typescript: "^5.9.3",
    },
  };
  return JSON.stringify(pkg, null, 2) + "\n";
}

export function generateTsConfig(): string {
  const config = {
    compilerOptions: {
      target: "ES2022",
      module: "Node16",
      moduleResolution: "Node16",
      outDir: "./dist",
      rootDir: "./src",
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      resolveJsonModule: true,
      types: ["node"],
    },
    include: ["src"],
  };
  return JSON.stringify(config, null, 2) + "\n";
}

export function generateGitignore(): string {
  return [
    "node_modules/",
    "dist/",
    ".env",
    ".env.*",
    "!.env.example",
    "*.log",
    ".DS_Store",
    "",
  ].join("\n");
}

/** Defaults are closed: loopback bind, localhost-only Host allowlist, no token. */
export function httpTransportEnvBlock(): string {
  return `
# ─── HTTP transport ──────────────────────────────────────────────────────────
# Port the Streamable HTTP server listens on.
MCP_PORT=3100

# Network interface to bind. Defaults to loopback (127.0.0.1) so the server is
# NOT reachable from other hosts. Set to 0.0.0.0 to expose it — but only after
# setting MCP_AUTH_TOKEN and widening MCP_ALLOWED_HOSTS below.
# MCP_BIND_HOST=127.0.0.1

# DNS-rebinding protection: comma-separated Host values the server accepts.
# Defaults to localhost/127.0.0.1 on MCP_PORT. When binding to a non-loopback
# host or running behind a proxy, list the public host:port here, e.g.
#   MCP_ALLOWED_HOSTS=mcp.example.com:3100
# MCP_ALLOWED_HOSTS=

# Optional comma-separated allowed Origin values (browser clients). Leave empty
# to skip Origin checking, e.g. MCP_ALLOWED_ORIGINS=https://app.example.com
# MCP_ALLOWED_ORIGINS=

# Bearer token required on every request (Authorization: Bearer <token>).
# STRONGLY RECOMMENDED: without it this server is unauthenticated, and anyone who
# can reach MCP_PORT can invoke every tool using its credentials.
# Generate one with:  node -e "console.log(crypto.randomUUID())"
# MCP_AUTH_TOKEN=replace-with-a-long-random-secret

# Session limits (the HTTP transport keeps one session per connected client).
#   MCP_MAX_SESSIONS   = concurrent sessions before new ones get 503 (default 1000)
#   MCP_SESSION_TTL_MS = idle session is reaped after this many ms (default 1800000 = 30m)
# MCP_MAX_SESSIONS=1000
# MCP_SESSION_TTL_MS=1800000
`;
}

export function generateEnvExample(
  usesSampling: boolean,
  transport: "stdio" | "http" = "stdio",
): string {
  let env = `# Rocket.Chat connection
ROCKETCHAT_URL=http://localhost:3000

# Credentials — the server acts as this user
ROCKETCHAT_USER=your-username
ROCKETCHAT_PASSWORD=your-password

# Or token auth (takes priority over user/password)
# ROCKETCHAT_AUTH_TOKEN=
# ROCKETCHAT_USER_ID=
`;
  if (usesSampling) {
    env += `
# Sampling steps request the MCP client's LLM, so no extra key is required when
# your MCP client supports sampling.
`;
  }
  if (transport === "http") {
    env += httpTransportEnvBlock();
  }
  return env;
}

export interface ReadmeOptions {
  platformName?: string;
  permissions?: string[];
  clientFileName?: string;
}

export function generateReadme(
  serverName: string,
  workflows: WorkflowDefinition[],
  endpoints: GeneratorEndpoint[],
  options: ReadmeOptions = {},
): string {
  const platformName = options.platformName ?? "Rocket.Chat";
  const clientFileName = options.clientFileName ?? "rc-client.ts";
  const date = new Date().toISOString().split("T")[0];
  const workflowRows = workflows
    .map((w) => {
      const features: string[] = [];
      if (w.usesSampling) features.push("AI");
      if (w.usesElicitation) features.push("Human-in-loop");
      const badge = features.length > 0 ? features.join(", ") : "Automation";
      return `| \`${escapeMarkdownCell(w.name)}\` | ${escapeMarkdownCell(
        w.description,
      )} | ${w.steps.length} | ${badge} |`;
    })
    .join("\n");
  const endpointRows = endpoints
    .map(
      (ep) =>
        `| \`${escapeMarkdownCell(ep.operationId)}\` | \`${escapeMarkdownCell(
          ep.method.toUpperCase(),
        )}\` | \`${escapeMarkdownCell(ep.path)}\` |`,
    )
    .join("\n");

  const permissionSection =
    options.permissions && options.permissions.length > 0
      ? `
## Required ${platformName} permissions

The account this server authenticates as needs the following permissions.
Grant them before running any workflow, or calls will fail with \`unauthorized\`.

${options.permissions.map((p) => `- \`${escapeMarkdownCell(p)}\``).join("\n")}
`
      : "";

  return `# ${serverName}

A workflow-based [MCP](https://modelcontextprotocol.io/) server for ${platformName},
generated by **mcp-server-generator**. Each tool runs a multi-step workflow that
chains API calls, AI sampling, and user confirmation behind one call.

> Generated on ${date}

## Quick start

\`\`\`bash
npm install
cp .env.example .env   # fill in your ${platformName} credentials
npm start
\`\`\`

## Development

\`\`\`bash
npm test         # run the generated workflow smoke tests
npm run build    # type-check and compile to dist/
\`\`\`

## Workflow tools

| Tool | Description | Steps | Features |
|------|-------------|-------|----------|
${workflowRows}

## API endpoints used

| operationId | Method | Path |
|-------------|--------|------|
${endpointRows}
${permissionSection}
## Project layout

\`\`\`
${serverName}/
├── src/
│   ├── server.ts       # entry point — wires tools to stdio transport
│   ├── ${clientFileName}    # ${platformName} HTTP client
│   ├── endpoints.ts    # operationId -> method + path
│   ├── engine/         # vendored workflow engine
│   ├── tools/          # one file per workflow
│   └── tests/          # one smoke test per workflow + shared setup
├── .env.example
├── package.json
├── tsconfig.json
└── README.md
\`\`\`

---

*Generated by mcp-server-generator.*
`;
}
